// Generated by ReScript, PLEASE EDIT WITH CARE


function className(font) {
  switch (font) {
    case /* Small */0 :
        return "text-sm";
    case /* Medium */1 :
        return "text-2xl";
    case /* Large */2 :
        return "text-6xl";
    
  }
}

function updatePreviewText($$event) {
  var textView = document.getElementById("textView");
  textView.innerText = $$event.target.value;
  
}

function updateFontOf(element, font) {
  element.classList.remove("text-sm", "text-2xl", "text-6xl");
  return element.classList.add(className(font));
}

function updatePreviewFont($$event) {
  var textView = document.getElementById("textView");
  var match = $$event.target.id;
  switch (match) {
    case "selectRegular" :
        return updateFontOf(textView, /* Medium */1);
    case "selectSmall" :
        return updateFontOf(textView, /* Small */0);
    default:
      return updateFontOf(textView, /* Large */2);
  }
}

var textEditor = document.getElementById("textEditor");

textEditor.addEventListener("input", updatePreviewText);

var radioBtn = document.getElementById("radio-text-size");

radioBtn.addEventListener("change", updatePreviewFont);

export {
  className ,
  updatePreviewText ,
  updateFontOf ,
  updatePreviewFont ,
  textEditor ,
  radioBtn ,
  
}
/* textEditor Not a pure module */
